import Head from "next/head";
import styles from "../styles/layout.module.css";

const Layout = ({
  refElement,
  favicon = "/favicon.ico",
  tabName,
  themeColor = "#000000",
  mainContainerClass,
  eventClick,
  children,
}) => {
  return (
    <div ref={refElement} onClick={eventClick}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content={themeColor} />
        <title>{tabName}</title>
        <link rel="icon" href={favicon} />
      </Head>

      <main className={`${styles.main} ${mainContainerClass}`}>{children}</main>
    </div>
  );
};

export default Layout;
